[window]
option_as_alt = "Both"

[font]
size = 12.0

[font.bold]
family = "MesloLGM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "FiraCode Nerd Font Mono"
# style = "Retina"
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001Bl"
# key = "Right"
# mods = "None"

# [[keyboard.bindings]]
# chars = "\u001B+"
# key = "Equals"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B-"
# key = "Minus"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B["
# key = "LBracket"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B]"
# key = "RBracket"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B\\"
# key = "Backslash"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bh"
# key = "H"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bj"
# key = "J"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bk"
# key = "K"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bl"
# key = "L"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bi"
# key = "I"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bc"
# key = "C"
# mods = "Alt"
